package com.task_flow.backend.enums;

public enum WorkflowEventType {
    WORKFLOW_STARTED,
    STEP_STARTED,
    STEP_COMPLETED,
    STEP_FAILED,
    STEP_SKIPPED,
    INTENT_CREATED,
    INTENT_COMPLETED,
    TIMER_SCHEDULED,
    TIMER_FIRED,
    CHILD_WORKFLOW_STARTED,
    CHILD_WORKFLOW_COMPLETED,
    AWAITING_SIGNAL,
    SIGNAL_RECEIVED,
    WORKFLOW_COMPLETED,
}
