spring:
  application:
  config:
    import: optional:file:.env[.properties]   
  name: backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: task-flow
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    root: INFO
    com.task_flow.backend: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
