spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
    username: postgres.igyrslrplsjsbtkmpwha
    password: apointy5liviu
  jpa:
    properties:
      hibernate:
        default_schema: task-flow
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    com.task_flow.backend: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
